/*
 * Writes js/config.js with the API keys of the web app (../.env), run it once before packaging:
 *   node samsung-tv/tools/config.mjs
 * js/config.js is ignored by git, like .env.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const envFile = path.join(root, '..', '.env')
const target = path.join(root, 'js', 'config.js')

const env = {}
if (existsSync(envFile)) {
  readFileSync(envFile, 'utf8').split('\n').forEach((line) => {
    const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/)
    if (match) { env[match[1]] = match[2].replace(/^["']|["']$/g, '') }
  })
} else {
  console.warn('No .env found in the project root, writing a config without API keys.')
}

const config = {
  traktApiKey: env.VITE_TRAKT_API_KEY || '',
  tmdbApiKey: env.VITE_TMDB_API_KEY || '',
  playerUrl: env.TV_PLAYER_URL || '',
  proxyUrl: env.TV_PROXY_URL || ''
}

writeFileSync(target, `// generated by tools/config.mjs, do not commit\nwindow.SM_CONFIG = ${JSON.stringify(config, null, 2)};\n`)

console.log(`Wrote ${path.relative(process.cwd(), target)}`)
console.log(`  Trakt API key (popular shows): ${config.traktApiKey ? 'yes' : 'missing'}`)
console.log(`  TMDB API key (play links):     ${config.tmdbApiKey ? 'yes' : 'missing'}`)
console.log(`  Player address (TV_PLAYER_URL): ${config.playerUrl ? 'yes' : 'not set, play links open in the browser'}`)
console.log(`  Stream proxy (TV_PROXY_URL):    ${config.proxyUrl || 'not set, streams need an IP address'}`)
