/*
 * showmaniac TV - settings.
 * API keys are not stored here, they come from js/config.js (generated by tools/config.mjs).
 */
(function () {
  'use strict';

  var SM = window.SM;
  var config = window.SM_CONFIG || {};

  SM.settings = {
    /**
     * Play link, keep in sync with watchUrl in src/components/ShowPast.vue
     * @example https://www.1shows.bz/tv/66292-big-little-lies?season=2&episode=1&streaming=true
     */
    playUrl: 'https://www.1shows.bz/tv/{tmdb}-{slug}?season={season}&episode={episode}&streaming=true',

    /**
     * Optional: address that is shown in the player of the app instead of opening the browser.
     * Either a page with a video player that may be embedded, or a video file/stream (mp4, m3u8).
     * Placeholders: {tmdb} {imdb} {tvdb} {slug} {season} {episode}
     * Empty: play links are opened in the browser of the TV.
     * To keep it out of git set TV_PLAYER_URL in .env and run tools/config.mjs.
     */
    playerUrl: config.playerUrl || '',

    /**
     * Optional: stream proxy in the home network (tools/proxy.mjs), e.g. http://192.168.0.32:5181
     * The video player of the TV only loads addresses with an IP address, video files and streams
     * with a host name are loaded through the proxy.
     */
    proxyUrl: config.proxyUrl || '',

    // on the TV the stream of the page is played by the video player of the TV once the episode plays
    playerNativeStreams: true,

    // the player clicks into the middle of the page if the video does not start by itself
    playerAutoClick: true,

    /**
     * Official streaming services, the detail screen shows a button for each one that has the show.
     * providers: names in the TMDB provider list of the country, e.g. "Joyn" also matches "Joyn Plus"
     * url: link for the show, {slug} is the name like "germanys-next-topmodel", {name} the plain name
     * verify: the url is the page of the show, the button only appears if it exists;
     *         searchUrl is used if TMDB lists the show but the page was not found
     * appId: the app of the service on the TV, it gets the link. Without the app the link is
     *        opened in the browser of the TV.
     * clickout: the address of the show is taken from the TMDB watch page, url is the fallback
     * payload: start data for the app instead of the link, {name} is a parameter of the address
     */
    country: 'AT',
    services: [{
      name: 'Joyn',
      providers: ['Joyn'],
      url: 'https://www.joyn.at/serien/{slug}',
      verify: true,
      searchUrl: 'https://www.joyn.at/suche?q={name}',
      appId: '2200MKoe7n.ZAPPNVOLLTVFREIGESTREAMT'
    }, {
      name: 'RTL+',
      providers: ['RTL+'],
      url: 'https://plus.rtl.de/suche?q={name}',
      appId: 'KbRHmu0vrC.TVNOWPREMIUM'
    }, {
      name: 'Netflix',
      providers: ['Netflix'],
      url: 'https://www.netflix.com/search?q={name}',
      appId: 'org.tizen.netflix-app'
    }, {
      name: 'Prime Video',
      providers: ['Amazon Prime Video'],
      clickout: true,
      payload: 'contentId={gti}', // the app ignores links, it opens the show with this start data
      url: 'https://www.primevideo.com/search?phrase={name}',
      appId: 'org.tizen.primevideo'
    }, {
      name: 'Disney+',
      providers: ['Disney Plus'],
      url: 'https://www.disneyplus.com/search?q={name}',
      appId: 'MCmYXNxgcu.DisneyPlus'
    }, {
      // TMDB calls Apple TV+ "Apple TV"; the app ignores the name in a search link
      name: 'Apple TV',
      providers: ['Apple TV'],
      clickout: true,
      url: 'https://tv.apple.com/search?term={name}',
      appId: 'com.samsung.tv.aria-video'
    }],

    // Samsung Internet on Tizen TVs, null lets the TV pick an app for the link
    browserAppIds: ['org.tizen.browser', null],

    // same public web config as src/firebase/config.js
    firebase: {
      apiKey: 'AIzaSyBUaXTM6-Y_ZbQlY_XbVye_Lfs8euJBqGI',
      databaseURL: 'https://showmaniac.firebaseio.com'
    },

    traktApiKey: config.traktApiKey || '',
    tmdbApiKey: config.tmdbApiKey || ''
  };
})();
