/*
 * showmaniac TV - settings.
 * API keys are not stored here, they come from js/config.js (generated by tools/config.mjs).
 */
(function () {
  'use strict';

  var SM = window.SM;
  var config = window.SM_CONFIG || {};

  SM.settings = {
    /**
     * Play link, keep in sync with watchUrl in src/components/ShowPast.vue
     * @example https://www.1shows.org/tv/66292-big-little-lies?season=2&episode=1&streaming=true
     */
    playUrl: 'https://www.1shows.org/tv/{tmdb}-{slug}?season={season}&episode={episode}&streaming=true',

    // Samsung Internet on Tizen TVs, null lets the TV pick an app for the link
    browserAppIds: ['org.tizen.browser', null],

    // same public web config as src/firebase/config.js
    firebase: {
      apiKey: 'AIzaSyBUaXTM6-Y_ZbQlY_XbVye_Lfs8euJBqGI',
      databaseURL: 'https://showmaniac.firebaseio.com'
    },

    traktApiKey: config.traktApiKey || '',
    tmdbApiKey: config.tmdbApiKey || ''
  };
})();
